[package]
name = "file2addr"
version = "0.1.0"
authors = ["Michael McKinnon <michael@clicknames.com.au>"]

[dependencies]
bitcoin = "0.10.6"
hex = "0.3.1"
rand = "0.3"
rust-crypto = "0.2.36"
secp256k1 = "0.6.3"
